sudo: required
services:
  - docker

before install:
  - docker build -t vkarmadocker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vkarmadocker/docker-react npm run test -- --coverage